@plr = player()


@hero = associative_array(
            'name': '§8Da§4mo§8n S§8alv§4at§8ore',
            'class': 'damonsalvatore',
            'sig': 'xDXChSmYO6TlIqoicC7sjuNyLBgKv03pzDfY3CYMQJYBMgseliEATmHQYXp6ec03wcNMCVMxPO8WC8LSt5WK6ULWwb3Hw3lHUXtK45cShWxjoBn13yVsXkCEAfIUUa4Li4n0F52mOsG6qnngRLTCT9aKms9NTgPPmcyWmB3qeFfjCfiL7QxIa42Pu4m9g8klu62JTLJFLuEXSMXEr25fvgHgjE1tUXC9z3pwPN/+mO9eHPfR5CHL1E8mOBXwluqjQCpWU8WakK/4kn1GDW+u5dDTPrupfTgWyHFGw91iZ/lMjYPdsxBQQTep9QJ+hykaf5h1hOFR+OP9kPVWrDCrG5WkHg7tQbwQfS+2lBvgUzYwoqNOrXGae3KToMgWusNHl1iDA2AtwDdPUMmNPVPPgdgMn1UJuy4XhDjY1d8HnfWltxC9cvHgPuQ/yqCzn3VJRSCwOGwQdZ8pf5VCvMAPIi57k7q7hqJdFD+cmIoy6OcAyqWU416uhdogdjMeBj3LSRP+AgeaVNSjaVbhA/yg1IvCso/8qduY2rMDJZ/llf+WgfWbs2GYe0ECsQNBsYkkpZBMgyP+A2RzdP1WG4Ay8VPKOXCj4YDWspSxxQD/PZ/dhD8n5yFlLmJehNKpkicFf+8N4URpAm/47Acrb+LF4lgeENtSNiUGNriNqGUGwWY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTUwMTI4NDc3NTMsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJGaXhTaGF4Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xYTc0NGRiYjMyYmNhNzkyN2JmYzYyN2Q1YzYxYmM1YTllZTVhZTM5ZjViNTU1ZjhiODE1YWM1Mzc3ZjBlOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Stefan i'll ruin your life for ever!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-8",
                "/carryplayer",
                "/dismountplayer",
                "/mindcontrol"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
            )
        )
